version: '3'

# Uses to test the sirius-chat container ad-hoc
# replace the environment variables to point
# to a running central elasticsearch + redis
# running them locally? your IP is a good choice for CHANGE_ME ;-)

services:
  # sirius-chat adhoc
  sirius-chat-sample:
    image: sirius-chat
    ports:
      - "80:80"
    environment:
      - REDIS_HOST=CHANGE_ME
      - REDIS_PORT=33001
      - ES_HOST=CHANGE_ME:33002
